language: c
sudo: false
addons:
  apt:
    packages:
      - debhelper
      - fakeroot
      - libpipeline-dev
      - pkg-config
      - perl
before_script:
  - git clone https://github.com/sstephenson/bats.git
  - cd bats && ./install.sh $HOME/bats && cd ..
  - export PATH=$PATH:$HOME/bats/bin
  - autoreconf -i
script:
  - ./configure --enable-silent-rules --disable-dependency-tracking
  - make all
  - make bats
compiler:
  - gcc
  - clang
